source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!
pod 'GoogleMaps'

def testing_pods
    pod 'Quick', '~> 0.9.0'
    pod 'Nimble', '~> 3.2.0'
end

target 'MapViewTests' do
    pod 'GoogleMaps'
    testing_pods
end

target 'MapViewUITests' do
    pod 'GoogleMaps'
    testing_pods
end