source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'

target 'MapView' do
    pod 'GoogleMaps'
end

target 'MapViewTests' do
    pod 'GoogleMaps'
end

target 'MapViewUITests' do
    pod 'GoogleMaps'
end